# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e3405536680871aceace162b205814ecd57b21cfb2279e2efb809f486f3657050eb0583236f5460cb492c54bfbd00efe6a1484775f65af491ef0028e74d75037

test:
  secret_key_base: e61e538d76faf83f83f069d960aa75c3bed7a3d69e129aa92c0323157cad828675163670ab853499f9c1d010c0000abb5c642d79d70ec1ff4178d18ea776af07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
